name: Ruyam Exclusive Web and APK Build
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Java Kurulumu
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Flutter Kurulumu
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Proje Altyapisini Onar ve Guncelle
        # Web ve Android altyapisini sifirdan kurar
        run: |
          rm -rf android web
          flutter create . --platforms android,web

      - name: Paketleri Getir
        run: flutter pub get

      - name: Web Sitesini Hazirla
        run: flutter build web --release

      - name: APK Olustur (Android)
        run: flutter build apk --debug

      - name: Web Dosyalarini Kaydet
        uses: actions/upload-artifact@v4
        with:
          name: web-sitesi-dosyalari
          path: build/web/

      - name: APK Kaydet
        uses: actions/upload-artifact@v4
        with:
          name: uygulama-dosyasi
          path: build/app/outputs/flutter-apk/app-debug.apk
          
