name: Ruyam-Final
on:
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Onar
        run: flutter create . --platforms web,android
      - name: Derle
        run: |
          flutter pub get
          flutter build web --release --base-href /Deneme/
          flutter build apk --debug
          
      - uses: actions/upload-artifact@v4
        with:
          name: tum-dosyalar
          path: |
            build/web/
            build/app/outputs/flutter-apk/app-debug.apk
            
