name: Flutter APK Build

on:
  push:
    branches: [ "main" ] # Senin ana dalın 'ana' olduğu için böyle kalsın
workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Java Kurulumu
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'
          
      - name: Flutter Kurulumu
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.0' # Stabil bir sürüm
          
      - name: Paketleri Getir
        run: flutter pub get
        
      - name: APK Oluştur
        run: flutter build apk --debug # Hızlı olması için debug sürümü

      - name: APK'yı Kaydet
        uses: actions/upload-artifact@v3
        with:
          name: uygulama-dosyasi
          path: build/app/outputs/flutter-apk/app-debug.apk
          
